name: "deploy"
on: 
  push:
    branches: [ main ]
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build
    - run: |
        git config --global user.name 'justintout'
        git commit -am "automated gh-pages build"
        git push --force