name: "deploy"
on: 
  push:
    branches: [ main ]
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build
    - run: |
        git config --global user.name 'justintout'
        git checkout --orphan gh-pages
        git reset --hard
        for p in ".parcel-cache" "dist" "node_modules"; do echo "${p}" >> .gitignore; done
        mv dist/* .
        git add .
        git commit -m "automated page build"
        git push --force origin gh-pages